import type { BandNameOption } from "./chooseBandName";

export const bandNameCatalog = [
  {
    id: "ultima-luz",
    bandName: "Última Luz",
    title: "Última Luz",
    text: "Suena a banda que convierte cualquier escenario chico en algo más grande.",
    badge: "+2 Carisma / +1 Fama",
    effects: { charisma: 2, fame: 1 },
    personalitySignals: ["ambition"],
  },
  {
    id: "ruido-santo",
    bandName: "Ruido Santo",
    title: "Ruido Santo",
    text: "Tiene algo contradictorio, medio místico y medio quilombero. Nadie sabe bien qué esperar.",
    badge: "+2 Creatividad / +1 Reputación",
    effects: { creativity: 2, reputation: 1 },
    personalitySignals: ["creativity", "rebellion"],
  },
  {
    id: "kilometro-cero",
    bandName: "Kilómetro Cero",
    title: "Kilómetro Cero",
    text: "No promete gloria. Promete empezar desde abajo y no olvidarse de dónde salieron.",
    badge: "+2 Reputación / +1 Salud",
    effects: { reputation: 2, health: 1 },
    personalitySignals: ["humble", "loyalty"],
  },
  {
    id: "barrio-electrico",
    bandName: "Barrio Eléctrico",
    title: "Barrio Eléctrico",
    text: "Huele a vereda mojada, cables pelados y canciones hechas para tocar fuerte.",
    badge: "+2 Fama / +1 Carisma",
    effects: { fame: 2, charisma: 1 },
    personalitySignals: ["rebellion"],
  },
  {
    id: "santos-electricos",
    bandName: "Santos Eléctricos",
    title: "Santos Eléctricos",
    text: "Un nombre con estampita, distorsión y olor a ensayo de domingo.",
    badge: "+2 Reputación / +1 Talento",
    effects: { reputation: 2, talent: 1 },
    personalitySignals: ["loyalty", "discipline"],
  },
  {
    id: "ultima-fila",
    bandName: "Última Fila",
    title: "Última Fila",
    text: "Para los que miran todo desde atrás y terminan entendiendo mejor la noche.",
    badge: "+2 Creatividad / +1 Salud",
    effects: { creativity: 2, health: 1 },
    personalitySignals: ["humble", "creativity"],
  },
  {
    id: "escupitajo",
    bandName: "Escupitajo",
    title: "Escupitajo",
    text: "No nació para caer bien. Nació para hacerse escuchar.",
    badge: "+2 Carisma / +1 Reputación",
    effects: {
      charisma: 2,
      reputation: 1,
    },
    personalitySignals: ["rebellion", "impulsive"],
  },
  {
    id: "humo-en-la-terminal",
    bandName: "Humo en la Terminal",
    title: "Humo en la Terminal",
    text: "Un nombre para salir de gira antes de tener plata para volver.",
    badge: "+2 Fama / +1 Creatividad",
    effects: { fame: 2, creativity: 1 },
    personalitySignals: ["fearless", "ambition"],
  },
  {
    id: "sin-permiso",
    bandName: "Sin Permiso",
    title: "Sin Permiso",
    text: "Medio arrogante, medio cierto. Ideal para pegar en un baño de bar.",
    badge: "+2 Fama / -1 Reputación",
    effects: { fame: 2, reputation: -1 },
    personalitySignals: ["egocentric", "ambition"],
  },
  {
    id: "la-fiebre-del-sur",
    bandName: "La Fiebre del Sur",
    title: "La Fiebre del Sur",
    text: "Tiene algo de épica barrial y algo de fiebre antes de subir al escenario.",
    badge: "+2 Carisma / +1 Creatividad",
    effects: { charisma: 2, creativity: 1 },
    personalitySignals: ["ambition", "creativity"],
  },
  {
    id: "los-invisibles",
    bandName: "Los Invisibles",
    title: "Los Invisibles",
    text: "Un nombre para tocar sin pedir foco y terminar quedándose con la sala.",
    badge: "+2 Reputación / +1 Creatividad",
    effects: { reputation: 2, creativity: 1 },
    personalitySignals: ["humble"],
  },
  {
    id: "mala-costumbre",
    bandName: "Mala Costumbre",
    title: "Mala Costumbre",
    text: "Corto, filoso y con pinta de haber nacido de una discusión.",
    badge: "+2 Carisma / +1 Reputación",
    effects: { charisma: 2, reputation: 1 },
    personalitySignals: ["impulsive", "rebellion"],
  },
  {
    id: "pulso-salvaje",
    bandName: "Pulso Salvaje",
    title: "Pulso Salvaje",
    text: "Directo al pecho. Si suenan así, nadie se va quieto.",
    badge: "+2 Talento / +1 Carisma",
    effects: { talent: 2, charisma: 1 },
    personalitySignals: ["discipline", "fearless"],
  },
  {
    id: "la-noche-miente",
    bandName: "La Noche Miente",
    title: "La Noche Miente",
    text: "Puede ser un hit, una advertencia o las dos cosas a la vez.",
    badge: "+2 Fama / +1 Salud",
    effects: { fame: 2, health: 1 },
    personalitySignals: ["pragmatic", "ambition"],
  },
  {
    id: "cenizas-de-neon",
    bandName: "Cenizas de Neón",
    title: "Cenizas de Neón",
    text: "Poético, nocturno y un poco dramático. Como todo primer demo honesto.",
    badge: "+3 Creatividad",
    effects: { creativity: 3 },
    personalitySignals: ["creativity", "authentic"],
  },
  {
    id: "motor-del-barrio",
    bandName: "Motor del Barrio",
    title: "Motor del Barrio",
    text: "No quiere sonar fino. Quiere arrancar aunque haga ruido.",
    badge: "+2 Talento / +1 Reputación",
    effects: { talent: 2, reputation: 1 },
    personalitySignals: ["discipline", "loyalty"],
  },
  {
    id: "nadie-aplaude-primero",
    bandName: "Nadie Aplaude Primero",
    title: "Nadie Aplaude Primero",
    text: "Un nombre largo para una banda que sabe incomodar al silencio.",
    badge: "+2 Reputación / +1 Fama",
    effects: { reputation: 2, fame: 1 },
    personalitySignals: ["authentic", "rebellion"],
  },
  {
    id: "alta-tension",
    bandName: "Alta Tensión",
    title: "Alta Tensión",
    text: "Pesado, exagerado y cero sutil. Hay gente que necesita exactamente eso.",
    badge: "+3 Carisma / -1 Salud",
    effects: { charisma: 3, health: -1 },
    personalitySignals: ["impulsive", "fearless"],
  },
  {
    id: "antes-del-ruido",
    bandName: "Antes del Ruido",
    title: "Antes del Ruido",
    text: "Como si alguien hubiera escrito una canción antes de saber tocarla.",
    badge: "+2 Creatividad / +1 Reputación",
    effects: { creativity: 2, reputation: 1 },
    personalitySignals: ["authentic", "creativity"],
  },
  {
    id: "los-que-vuelven-tarde",
    bandName: "Los Que Vuelven Tarde",
    title: "Los Que Vuelven Tarde",
    text: "Tiene barrio, noche y una excusa que nadie va a creer del todo.",
    badge: "+2 Carisma / +1 Fama",
    effects: { charisma: 2, fame: 1 },
    personalitySignals: ["fearless", "loyalty"],
  },
  {
    id: "sistema-nervioso",
    bandName: "Sistema Nervioso",
    title: "Sistema Nervioso",
    text: "Suena tenso, moderno y listo para romper una sala demasiado ordenada.",
    badge: "+2 Talento / +1 Creatividad",
    effects: { talent: 2, creativity: 1 },
    personalitySignals: ["discipline", "rebellion"],
  },
  {
    id: "verdugos",
    bandName: "Verdugos",
    rarity: "special",
    title: "Verdugos",
    text: "Un nombre que no pide permiso. Corta, golpea y se hace recordar.",
    badge: "+2 Carisma / +1 Reputación",
    effects: {
      charisma: 2,
      reputation: 1,
    },
    personalitySignals: ["rebellion", "ambition"],
  },
] satisfies readonly BandNameOption[];
