import type { NarrativeConsequence } from "@/game/narrativeConsequences";

export const firstRecitalConsequences = [
  {
    eventId: "first-recital",
    optionId: "open-with-everything",
    eyebrow: "Después del primer acorde",
    title: "El bar entendió rápido",
    text: "El primer tema entró como una patada elegante. Algunos dejaron de hablar a mitad de frase, otros se acercaron sin darse cuenta. No fue un recital prolijo ni perfecto, pero durante esos primeros minutos nadie dudó de que la banda quería ser recordada.",
    tone: "neutral",
    cta: "Bajar del escenario",
  },
  {
    eventId: "first-recital",
    optionId: "build-the-show",
    eyebrow: "Después del último tema",
    title: "La noche fue creciendo",
    text: "Al principio el público escuchó con distancia, como si todavía estuviera decidiendo si quedarse. Canción tras canción la sala empezó a entrar en clima. Para el final, los aplausos no fueron una sorpresa: parecían la consecuencia natural de haber construido el show con paciencia.",
    tone: "neutral",
    cta: "Bajar del escenario",
  },
  {
    eventId: "first-recital",
    optionId: "improvise",
    eyebrow: "Después del desorden",
    title: "Nadie sabía cómo terminaba",
    text: 'La improvisación duró bastante más de lo que debía. El guitarrista sonrió. El bajista no entendió cómo volver a la canción. Desde una mesa del fondo un borracho gritó: "¡Esa no estaba ensayada!". Tenía razón.',
    tone: "negative",
    cta: "Bajar del escenario",
  },
  {
    eventId: "first-recital",
    optionId: "introduce-the-band",
    eyebrow: "Después de las presentaciones",
    title: "Los nombres quedaron dando vueltas",
    text: "Antes de tocar, cada integrante tuvo un lugar bajo la luz. La gente respondió con sonrisas, silbidos y algún aplauso perdido. El recital empezó menos como una exhibición y más como una promesa compartida: si algún día esto crece, nadie va a poder decir que empezó solo.",
    tone: "positive",
    cta: "Bajar del escenario",
  },
  {
    eventId: "first-recital",
    optionId: "play-known-cover",
    eyebrow: "Después del estribillo",
    title: "El público cantó el cover",
    text: "Durante tres minutos el bar cantó con ustedes. Cuando empezaron los temas propios volvieron las conversaciones. Igual, por un rato, sintieron que el escenario era suyo.",
    tone: "positive",
    cta: "Bajar del escenario",
  },
  {
    eventId: "first-recital",
    optionId: "say-nothing",
    eyebrow: "Después del silencio",
    title: "No hizo falta explicar nada",
    text: "No hubo saludo largo ni frase para ganar simpatía. Solo el ruido justo antes del primer golpe. Ese silencio volvió más pesados los instrumentos y más claras las canciones. La banda no pidió atención: la ocupó con música.",
    tone: "neutral",
    cta: "Bajar del escenario",
  },
  {
    eventId: "first-recital",
    optionId: "look-at-bandmates",
    eyebrow: "Después de mirarse",
    title: "Duró un segundo",
    text: "Se miraron antes de empezar. Fue el momento más coordinado de toda la noche.",
    tone: "negative",
    cta: "Bajar del escenario",
  },
  {
    eventId: "first-recital",
    optionId: "bring-crowd-forward",
    eyebrow: "Después del grito",
    title: "Cuarenta personas hicieron ruido de más",
    text: "El pedido movió la sala. Los tímidos dieron dos pasos, los amigos empujaron desde atrás y el escenario dejó de sentirse tan lejos. No eran cuatrocientas personas, pero durante algunos temas el bar tuvo esa energía: la de una banda que todavía no llena lugares, pero ya sabe achicarlos.",
    tone: "positive",
    cta: "Bajar del escenario",
  },
  {
    eventId: "first-recital",
    optionId: "tune-once-more",
    eyebrow: "Después de afinar",
    title: "Treinta segundos también cuentan",
    text: "La espera fue corta, pero se sintió larga arriba del escenario. Después entró el primer acorde y todo tuvo un poco más de centro. No todos notaron la diferencia, pero vos sí. A veces la identidad de una banda empieza en esa terquedad pequeña: querer que suene como tiene que sonar.",
    tone: "neutral",
    cta: "Bajar del escenario",
  },
  {
    eventId: "first-recital",
    optionId: "dedicate-first-song",
    eyebrow: "Después de la dedicatoria",
    title: "Los de abajo también tocaron",
    text: "Lo dedicaste a todos los que siempre los bancaron. Tu mamá lloró. Tu papá filmó todo el recital en vertical. Los demás siguieron tomando cerveza.",
    tone: "neutral",
    cta: "Bajar del escenario",
  },
] satisfies readonly NarrativeConsequence[];
