import type { NarrativeConsequence } from "@/game/narrativeConsequences";

export const firstInternalConflictConsequences = [
  {
    eventId: "first-internal-conflict",
    optionId: "start-without-him",
    eyebrow: "Después de arrancar sin él",
    title: "La banda aprendió a no esperar",
    text: "El ensayo empezó con un hueco raro, como una silla vacía en una cena familiar. Cuando llegó, nadie frenó para explicarle nada. Se enchufó en silencio y trató de seguir el tema desde la mitad. Sonaron mejor de lo esperado, pero algo cambió: desde ese día, llegar tarde dejó de ser gracioso y empezó a tener consecuencias.",
    tone: "neutral",
    cta: "Seguir tocando",
  },
  {
    eventId: "first-internal-conflict",
    optionId: "wait-and-talk",
    eyebrow: "Después de esperarlo",
    title: "La charla llegó tarde, pero llegó",
    text: "Lo esperaron con bronca contenida y mates demasiado lavados. Cuando apareció, nadie hizo chistes. Hablaron torpe, se pisaron, alguno exageró y otro pidió bajar un cambio. No quedó todo resuelto, pero por primera vez el problema tuvo nombre. La banda salió menos liviana, pero un poco más adulta.",
    tone: "positive",
    cta: "Volver a ensayar",
  },
  {
    eventId: "first-internal-conflict",
    optionId: "set-fifteen-minute-rule",
    eyebrow: "Después de poner una regla",
    title: "Quince minutos se volvieron ley",
    text: "La regla parecía chica, casi burocrática, pero ordenó la sala. Si alguien llegaba tarde, el ensayo arrancaba igual. Nadie tenía que adivinar humores ni negociar cada martes. La banda perdió un poco de caos romántico y ganó algo más raro: previsibilidad.",
    tone: "positive",
    cta: "Contar hasta quince",
  },
  {
    eventId: "first-internal-conflict",
    optionId: "call-him-out",
    eyebrow: "Después de decírselo de frente",
    title: "La sala quedó helada",
    text: "Se lo dijiste apenas entró y la frase cayó como trompada. Él se defendió, otro intentó mediar y durante un rato nadie tocó nada. Fue incómodo y medio brutal. Pero también quedó claro que la banda ya no podía sobrevivir a pura indirecta.",
    tone: "negative",
    cta: "Bajar el volumen",
  },
  {
    eventId: "first-internal-conflict",
    optionId: "make-a-joke",
    eyebrow: "Después del aplauso irónico",
    title: "El chiste tapó la bronca",
    text: "La ovación falsa hizo reír a todos, incluso a él. Durante diez minutos pareció que el problema se había evaporado. Después arrancaron a tocar y la misma molestia volvió, apenas disfrazada. La banda conservó el humor, pero empezó a sospechar que algunos chistes eran discusiones con maquillaje.",
    tone: "neutral",
    cta: "Reírse menos fuerte",
  },
  {
    eventId: "first-internal-conflict",
    optionId: "ask-what-is-going-on",
    eyebrow: "Después de preguntar",
    title: "La demora tenía historia",
    text: "Cuando le preguntaste qué le pasaba, no contestó enseguida. Después habló de laburo, bondis perdidos, cansancio y una vida que no siempre entraba prolija en el horario de ensayo. Nadie sabía bien qué hacer con esa información. La banda no justificó todo, pero entendió algo importante: un integrante también trae su mundo a la sala.",
    tone: "positive",
    cta: "Escuchar un poco más",
  },
  {
    eventId: "first-internal-conflict",
    optionId: "move-rehearsal-time",
    eyebrow: "Después de cambiar el horario",
    title: "La solución fue menos épica que útil",
    text: "Corrieron el ensayo una hora y, contra todo pronóstico, funcionó. No hubo discurso, ni abrazo, ni escena de película. Solo llegaron más o menos a tiempo y tocaron más. A veces una banda no necesita una revolución interna: necesita mirar el calendario sin hacerse la superada.",
    tone: "positive",
    cta: "Anotar el nuevo horario",
  },
  {
    eventId: "first-internal-conflict",
    optionId: "record-without-him",
    eyebrow: "Después de grabar sin él",
    title: "El audio dijo lo suyo",
    text: "Le mandaron la grabación del ensayo y no agregaron mucho más. Se escuchaba crudo, incompleto, pero vivo. Al día siguiente respondió con un mensaje corto: 'lo escuché'. En el próximo ensayo llegó antes que la mitad de la banda. Nadie festejó. Eso también fue parte del acuerdo.",
    tone: "positive",
    cta: "Guardar la toma",
  },
  {
    eventId: "first-internal-conflict",
    optionId: "change-time-for-him",
    eyebrow: "Después de mentirle el horario",
    title: "La trampa funcionó demasiado bien",
    text: "Le dijeron que el ensayo era unmedia hora antes y apareció casi puntual al horario real. La banda lo miró entrar como si hubiera descubierto el fuego. Fue efectivo, sí. También dejó una duda medio fea: si para funcionar necesitaban engañarse, capaz el problema era más grande que una agenda.",
    tone: "neutral",
    cta: "No confesar todavía",
  },
  {
    eventId: "first-internal-conflict",
    optionId: "threaten-replacement",
    eyebrow: "Después de decir reemplazo",
    title: "La palabra quedó colgada",
    text: "Nadie volvió a tocar igual esa noche. La amenaza ordenó la puntualidad, pero metió otro veneno en la sala: la idea de que cualquiera podía ser descartable. La banda ganó tensión y perdió inocencia. A veces crecer también es aprender qué palabras no vuelven atrás.",
    tone: "negative",
    cta: "Medir las palabras",
  },
  {
    eventId: "first-internal-conflict",
    optionId: "make-him-open-room",
    eyebrow: "Después de darle la llave",
    title: "La responsabilidad hizo ruido en el bolsillo",
    text: "La semana siguiente llegó primero. Abrió la sala, prendió las luces y se quedó esperando al resto con una mezcla de orgullo y cara de sueño. No se volvió perfecto, porque nadie se vuelve perfecto por tener una llave. Pero entendió que la banda también podía depender de él para algo más que llegar cuando podía.",
    tone: "positive",
    cta: "Entrar a la sala",
  },
  {
    eventId: "first-internal-conflict",
    optionId: "split-rehearsal-cost",
    eyebrow: "Después de cobrar la hora",
    title: "La plata hizo hablar a todos",
    text: "Cuando apareció el tema de pagar la hora perdida, la discusión se volvió menos filosófica y más incómoda. Nadie quería ser contador de una banda under, pero tampoco querían seguir pagando silencios ajenos. La relación quedó más fría, aunque la próxima vez todos miraron el reloj de otra manera.",
    tone: "negative",
    cta: "Cerrar la cuenta",
  },
  {
    eventId: "first-internal-conflict",
    optionId: "let-it-pass",
    eyebrow: "Después de dejarlo pasar",
    title: "El silencio ocupó más lugar",
    text: "No dijeron nada. Ensayaron poco, se rieron menos y cada pausa sonó como una conversación pendiente. Por afuera parecía que la banda seguía igual. Por adentro, algo se había corrido apenas unos centímetros. Lo suficiente para que todos lo sintieran, no tanto como para animarse a nombrarlo.",
    tone: "negative",
    cta: "Mirar para otro lado",
  },
  {
    eventId: "first-internal-conflict",
    optionId: "band-meeting",
    eyebrow: "Después de la reunión",
    title: "La banda habló sin esconderse detrás del ruido",
    text: "Sin instrumentos, quedaron expuestos. Hablaron de horarios, ganas, miedos y de esa pregunta que nadie quería hacer: si todos estaban empujando para el mismo lado. No fue una reunión prolija, pero sí necesaria. Cuando volvieron a tocar, sonaron un poco más serios. No más felices: más conscientes.",
    tone: "positive",
    cta: "Volver al volumen",
  },
  {
    eventId: "first-internal-conflict",
    optionId: "turn-late-entry-into-show",
    eyebrow: "Después de convertirlo en escena",
    title: "El defecto se volvió parte del personaje",
    text: "Lo que empezó como un problema terminó convertido en una entrada absurda. En el siguiente recital apareció tarde a propósito, con la banda estirando la intro y el público mirando sin entender hasta que empezó a aplaudir. Funcionó. También fue peligroso: cuando una banda aprende a vender sus defectos, a veces se olvida de arreglarlos.",
    tone: "neutral",
    cta: "Dejar que entre",
  },
] satisfies readonly NarrativeConsequence[];
