import type { NarrativeConsequence } from "@/game/narrativeConsequences";

export const firstReviewConsequences = [
  {
    eventId: "first-review",
    optionId: "prove-them-wrong",
    eyebrow: "Después de cerrar Instagram",
    title: "La bronca entró al ensayo",
    text: "No contestaste nada, pero la reseña se metió en la sala como un quinto integrante bastante molesto. El próximo ensayo salió más fuerte, más tenso y con menos chistes entre tema y tema. Nadie lo dijo en voz alta, pero todos estaban tocando contra esa frase: una banda más del montón.",
    tone: "neutral",
    cta: "Subir el volumen",
  },
  {
    eventId: "first-review",
    optionId: "share-and-thank",
    eyebrow: "Después del agradecimiento",
    title: "La cuenta respondió con respeto",
    text: "Compartiste la reseña y agradeciste la sinceridad. La cuenta contestó con un mensaje buena onda y algunos seguidores dejaron comentarios tibios, que en el under ya cuentan como aplausos. A la banda le dolió igual, pero dolió menos saber que podían recibir un golpe sin hacer papelones.",
    tone: "positive",
    cta: "Seguir escuchando",
  },
  {
    eventId: "first-review",
    optionId: "reply-publicly",
    eyebrow: "Después de responder",
    title: "El comentario se llenó de ruido",
    text: "La respuesta pública prendió una discusión chica, intensa y completamente desproporcionada. Tres personas defendieron a la banda, dos dijeron que la crítica tenía razón y uno comentó solo para pedir que escuchen su demo. La reseña tuvo más movimiento que el recital. No era ideal, pero ya nadie podía decir que no existían.",
    tone: "negative",
    cta: "Cerrar los comentarios",
  },
  {
    eventId: "first-review",
    optionId: "pretend-not-to-care",
    eyebrow: "Después de fingir calma",
    title: "Nadie la nombró, todos la pensaron",
    text: "Hiciste como que la reseña no importaba y la banda aceptó el pacto tácito: no hablar del tema. Funcionó durante media hora. Después alguien afinó mal y otro tiró: 'capaz el pibe de Instagram tenía un punto'. Se rieron. La herida seguía ahí, pero por lo menos ya no mandaba.",
    tone: "neutral",
    cta: "Dejarla pasar",
  },
  {
    eventId: "first-review",
    optionId: "ask-for-feedback",
    eyebrow: "Después del mensaje privado",
    title: "La crítica tuvo letra chica",
    text: "Pediste más detalles y la respuesta llegó sin mala leche: voces tapadas, finales apurados, un tema que parecía terminar tres veces. Fue incómodo leerlo, como escuchar una grabación propia. Pero la banda salió del ensayo con una lista concreta y menos fantasmas dando vueltas.",
    tone: "positive",
    cta: "Anotar lo útil",
  },
  {
    eventId: "first-review",
    optionId: "ignore-review",
    eyebrow: "Después de seguir como si nada",
    title: "El feed siguió bajando",
    text: "No hicieron nada. La publicación quedó ahí, entre una foto de una banda shoegaze de Morón y un reel de un guitarrista tocando un solo de Van Halen. A los dos días casi nadie la veía. La banda siguió ensayando. A veces la dignidad también es no convertir cada comentario en un incendio.",
    tone: "neutral",
    cta: "Ensayar mañana",
  },
  {
    eventId: "first-review",
    optionId: "make-fun",
    eyebrow: "Después del chiste",
    title: "Por ahora se volvió frase",
    text: "La historia con 'Por ahora' circuló más que la reseña original. Algunos se rieron con ustedes, otros pensaron que estaban agrandados para una banda que todavía carga sus propios equipos. El baterista propuso poner la frase en una remera. Nadie supo si era una buena idea o una amenaza.",
    tone: "neutral",
    cta: "Reírse un rato",
  },
  {
    eventId: "first-review",
    optionId: "invite-reviewer",
    eyebrow: "Después de la invitación",
    title: "La puerta quedó abierta",
    text: "El mensaje sorprendió al de la cuenta. Contestó que si podía, iba. La banda discutió diez minutos si eso era madurez, marketing o ganas de revancha con público. Probablemente las tres. Por primera vez, el próximo recital tenía a alguien esperando una respuesta.",
    tone: "positive",
    cta: "Preparar el próximo",
  },
  {
    eventId: "first-review",
    optionId: "read-with-band",
    eyebrow: "Después de leerla entre todos",
    title: "La banda eligió no romperse",
    text: "La reseña cayó en el medio del ensayo y cada frase tuvo dueño imaginario. El cantante miró al piso, el guitarrista se defendió antes de que lo acusaran y el bajista pidió leerla de nuevo. Fue incómodo, pero nadie se fue. A veces una banda empieza a ser banda cuando aprende a bancarse una verdad fea en la misma sala.",
    tone: "positive",
    cta: "Volver a tocar",
  },
  {
    eventId: "first-review",
    optionId: "write-a-song",
    eyebrow: "Después de escribir con bronca",
    title: "La crítica encontró melodía",
    text: "La frase que más dolía terminó convertida en estribillo. No era elegante, ni sutil, ni apta para gente que pide permiso antes de gritar. Pero tenía algo. En el ensayo, cuando la tocaron completa, la banda se miró distinto: por primera vez una cachetada de afuera había vuelto hecha canción.",
    tone: "positive",
    cta: "Guardar esa letra",
  },
] satisfies readonly NarrativeConsequence[];
