import type { NarrativeConsequence } from "@/game/narrativeConsequences";

export const firstMoneyConsequences = [
  {
    eventId: "first-money",
    optionId: "buy-working-cables",
    eyebrow: "Después de pasar por la casa de música",
    title: "El cable dejó de meter miedo",
    text: "Compraste cables nuevos y la banda los miró como si fueran instrumentos de colección. En el ensayo siguiente no hubo chispazos, cortes raros ni ese zumbido que parecía una heladera poseída.",
    tone: "positive",
    cta: "Volver al ensayo",
  },
  {
    eventId: "first-money",
    optionId: "print-flyers",
    eyebrow: "Después de la imprenta barrial",
    title: "El barrio amaneció empapelado",
    text: "A la mañana siguiente el nombre de la banda apareció en paradas de bondi, postes, persianas y una carnicería que no pidió permiso pero tampoco se quejó. Un vecino arrancó un afiche para anotar una lista de compras. Otro preguntó si tocaban cumbia. No era fama, pero ya era ruido en la vereda.",
    tone: "positive",
    cta: "Seguir pegando",
  },
  {
    eventId: "first-money",
    optionId: "split-and-go-home",
    eyebrow: "Después de guardar el billete",
    title: "La plata llegó entera a casa",
    text: "Volviste con tu parte en el bolsillo y una tranquilidad medio absurda. No compraste nada épico, no invitaste a nadie, no saliste en ninguna anécdota gloriosa. Pero cuando dejaste el billete arriba de la mesa, entendiste algo: esa noche la música, aunque fuera poquito, había pagado.",
    tone: "neutral",
    cta: "Guardar el recuerdo",
  },
  {
    eventId: "first-money",
    optionId: "make-tshirts",
    eyebrow: "Después del primer encargo",
    title: "Las remeras salieron torcidas",
    text: "Las primeras remeras llegaron con la tinta un poco corrida y el logo apenas inclinado, como si también hubiera vuelto tarde del recital. La banda al menos tenía una prueba de existencia.",
    tone: "positive",
    cta: "Doblar las remeras",
  },
  {
    eventId: "first-money",
    optionId: "buy-beer",
    eyebrow: "Después de la última ronda",
    title: "La noche se fue de control amable",
    text: "La plata duró menos que el solo del guitarrista. Hubo brindis, promesas exageradas y una discusión seria sobre si algún día iban a tocar en River o en una parrilla con escenario. A la mañana siguiente nadie tenía un peso, pero todos recordaban la frase: 'esto recién empieza'. Nadie recordaba quién la dijo.",
    tone: "negative",
    cta: "Buscar agua",
  },
  {
    eventId: "first-money",
    optionId: "first-date",
    eyebrow: "Después de animarte",
    title: "La cita tuvo más feedback que el retorno",
    text: "Invitaste a esa persona y la salida arrancó bien hasta que intentaste explicar por qué una banda con cuarenta espectadores ya era una señal del destino. Se rió, que era mejor que irse. No quedó claro si hubo romance, amistad o material para una canción incómodamente específica.",
    tone: "neutral",
    cta: "No sobreanalizar",
  },
  {
    eventId: "first-money",
    optionId: "supporters-asado",
    eyebrow: "Después del asado de agradecimiento",
    title: "La mesa también era parte de la banda",
    text: "Cayeron el técnico, el amigo del flete, la que prestó el micrófono y dos personas que nadie supo ubicar pero trajeron postre. Entre humo, asado y charla, la banda entendió que no había llegado sola al primer escenario. En el under, a veces la épica viene en fuente de aluminio.",
    tone: "positive",
    cta: "Un aplauso para el asador",
  },
  {
    eventId: "first-money",
    optionId: "buy-stage-clothes",
    eyebrow: "Después de probarte el look",
    title: "El espejo exageró un poco",
    text: 'Compraste algo para tocar y te lo probaste frente al espejo con cara de festival internacional. En el próximo ensayo el guitarrista te miró dos segundos y dijo: "Ahora solo falta aprender a tocar." No cambiaba el sonido, pero cuando uno se empieza a vestir como si tuviera escenario, algo en la cabeza camina distinto.',
    tone: "neutral",
    cta: "Que empiece el show",
  },
  {
    eventId: "first-money",
    optionId: "fix-drummers-van",
    eyebrow: "Después del taller mecánico",
    title: "La camioneta resucitó tosiendo",
    text: "La camioneta del baterista volvió a arrancar con un ruido que no inspiraba confianza, pero arrancó. El mecánico dijo 'tira un tiempo', que en idioma de taller significa misterio. La banda celebró como si hubieran comprado un micro de gira. Por ahora alcanzaba con no empujarla.",
    tone: "positive",
    cta: "Cargar los equipos",
  },
  {
    eventId: "first-money",
    optionId: "family-dinner",
    eyebrow: "Después de la cena familiar",
    title: "La familia guardó el gesto",
    text: "Llevaste a cenar a la familia y la cuenta se pagó con plata ganada tocando. Tu viejo te preguntó cuándo ibas a buscar un laburo. Tu vieja lo miró como mala cara. Nadie entendía del todo el plan, pero esa noche dejaron de mirarlo como un capricho y empezaron a mirarlo como una historia.",
    tone: "positive",
    cta: "Volver a casa",
  },
] satisfies readonly NarrativeConsequence[];
